### ISSUE TITLE
Q: Can we host on dreamhost from Github instead of Filezilla

### ISSUE THREAD

**Issue by DandyReyes** [USUGraffix/client#19]

**Comment by zcam007** [comment]
Working on it.

**Comment by zcam007** [comment]
Here are the few links that I though will be useful.

[#1](https://help.dreamhost.com/hc/en-us/articles/216445197-Pushing-your-local-Git-repository-to-a-DreamHost-server-Linux-Mac-OS-X)
[#2](https://help.dreamhost.com/hc/en-us/articles/115000684492-Using-Git-for-web-development)
[#3](https://medium.com/@marineboudeau/deploy-static-sites-with-git-to-servers-like-dreamhost-8d15e2b6bc41)

**Comment by zcam007** [comment]
## Uploading files to Dreamhost through Github
> Step 1

Clone repository from **USUGraffix** Github organization from [here](https://github.com/USUGraffix/calstatelausu.org) to your local folder using `git clone` command. For more information regarding clone, click [here](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/cloning-a-repository).

> Step 2

Navigate to your git repository on your local computer, and then push to the remote repository on your DreamHost server.
```
[local ~]$ git add .
[local ~]$ git commit -m "YOUR COMMIT MESSAGE"
[local ~]$ git remote add dreamhost ssh://usugraffix@calstatelausu.org/~/calstatelausu.org.git
[local ~]$ git push -u dreamhost master 
```

Enter the dreamhost server password available in the binder.

You should see the following response:

```
Counting objects: 3, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 200 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To ssh://usugraffix@calstatelausu.org/~/calstatelausu.org.git
* [new branch] master -> master
```

Since there are [post-receive hooks](https://git-scm.com/docs/githooks#post-receive) already written, the files will be copied/replaced to the live website folder and the changes will be live on the website immediately.
